#!/bin/bash

#:MIMIC=gw
#:ALIAS=_proxy

# Available environment variables
# MIMIC_ROOT_DIR     Application root folder [~/.mimic-a]
# MIMIC_B_DIR        Folder that contains mimic binaries
# MIMIC_A_DIR        Folder that contains current mimic aliases like eg: --log, --start, reload
# MIMIC_SHRD_DIR     Folder that contains shared functions that are sourced into alias environment
# MIMIC_CALLER       Called executable name(mimic) like git / netstat / ifconfig
# MIMIC_BIN          Original executable path /usr/local/bin/git
# MIMIC_ALIAS        Called alias name like: git --log  --log is alias

## One line help info
function alias_help(){
    echo "Proxy for gradlew"
}

## Multiline help doc for this alias
function alias_usage(){
   echo "USAGE: ${MIMIC_CALLER} [arg1 [arg2 [...[argN]]]]"
}

## Alias worker
#  If alias is prefixed with ! ( git ! log )
#  will be executed with original binary as /usr/bin/git log
##
function alias_do(){
  # Add/Modify/Preprocess/Postprocess parameters or functionality
  # Make original call
  if [ -x ./gradlew ];then
  ./gradlew ${MIMIC_ALIAS} $*
  else
    echo "Current folder does not contain ./gradlew executable" && exit 1
  fi
}
