#!/bin/bash

## One line help info
function alias_help(){
    echo "List available mimics"
}

## Help doc for this alias
function alias_usage(){
   echo "USAGE: ${MIMIC_CALLER} ${MIMIC_ALIAS} [arg1 [arg2 [...[argN]]]]"
}

## Current alias worker
function alias_do(){
  alias_help
  for avail_mimic in `ls $MIMIC_A_PATH`;
  do
    echo "  $avail_mimic"
  done
}
