#!/bin/bash

## One line help info
function alias_help(){
    echo "--mimic-edit tool for editing mimic aliases"
}

## Help doc for this alias
function alias_usage(){
   echo "USAGE: [mimic] ${MIMIC_ALIAS} [alias_name]
   Edit alias
"
}


# Current alias worker
function alias_do(){
  echo "Nothing to edit from here"
  echo "  `alias_help`"
  echo "  `alias_usage`"
}


