#!/bin/bash

#:MIMIC
#:ALIAS

# Available environment variables
# MIMIC_ROOT_DIR     Application root folder [~/.mimic-a]
# MIMIC_B_DIR        Folder that contains mimic binaries
# MIMIC_A_DIR        Folder that contains current mimic aliases like eg: --log, --start, reload
# MIMIC_SHRD_DIR     Folder that contains shared functions that are sourced into alias environment
# MIMIC_CALLER       Called executable name(mimic) like git / netstat / ifconfig
# MIMIC_BIN          Original executable path /usr/local/bin/git
# MIMIC_ALIAS        Called alias name like: git --log  --log is alias

## One line help info
function alias_help(){
    echo "alias handler for ${MIMIC_BIN} ${1}"
}

## Multiline help doc for this alias
function alias_usage(){
   echo "USAGE: ${MIMIC_CALLER} ${1} [arg1 [arg2 [...[argN]]]]"
}

## Alias worker
#  If alias is prefixed with ! ( git ! log )
#  will be executed with original binary as /usr/bin/git log
##
function alias_do(){
  local U_EDITOR="$1";
  local U_EDITOR_PATH="";
  while true;
  do
   read_user_arg "U_EDITOR" "Which editor would you like to use for editing aliases?"
   U_EDITOR_PATH="`which $U_EDITOR 2>/dev/null`"
   if ! [ -z "$U_EDITOR_PATH" ] || [ -x "$U_EDITOR" ] || [ -f "$U_EDITOR" ];then
     U_EDITOR_PATH="$U_EDITOR"
     if ! [ -f "$U_EDITOR" ];then
       U_EDITOR_PATH="`which $U_EDITOR`"
     fi
     echo "Saving $U_EDITOR_PATH as a default editor"
     echo "$U_EDITOR_PATH" > $MIMIC_CORE_DIR/mimic-editor.txt
     echo "Done"
     return;
   fi
  done
  date
}
