#!/bin/bash

#:MIMIC=amz
#:ALIAS=test

# Available environment variables
# MIMIC_ROOT_DIR     Application root folder [~/.mimic-a]
# MIMIC_B_DIR        Folder that contains mimic binaries
# MIMIC_A_DIR        Folder that contains current mimic aliases like eg: --log, --start, reload
# MIMIC_SHRD_DIR     Folder that contains shared functions that are sourced into alias environment
# MIMIC_CALLER       Called executable name(mimic) like git / netstat / ifconfig
# MIMIC_BIN          Original executable path /usr/local/bin/git
# MIMIC_ALIAS        Called alias name like: git --log  --log is alias

## One line help info
function alias_help(){
    echo "alias handler for ${MIMIC_BIN} ${1}"
}

## Multiline help doc for this alias
function alias_usage(){
   echo "USAGE: ${MIMIC_CALLER} ${1} [arg1 [arg2 [...[argN]]]]"
}

## Alias worker
#  If alias is prefixed with ! ( git ! log )
#  will be executed with original binary as /usr/bin/git log
##
function alias_do(){
  local queueName="$1"
  local propName="$2"
  local queuesPipe=""

  read_stdin_pipe "queuesPipe"
  if ! [ -z "$queueName" ] && [ -z "$queuesPipe" ];then
    # There's pipe with queue names
    queuesPipe="$queueName"
    queueName=""
  elif ! [ -z "$queuesPipe" ] && ! [ -z "$queueName" ];then
    propName="$queueName"
    queueName=""
  fi

  for qName in $queuesPipe;
  do
    if [ -z "$propName" ];then
      aws sqs get-queue-attributes --attribute-names All --queue-url $qName
    else
      aws sqs get-queue-attributes --attribute-names All --queue-url $qName | grep $propName
    fi
  done
}
