#!/bin/bash

#:MIMIC=react
#:ALIAS=init-ts

# Available environment variables
# MIMIC_ROOT_DIR     Application root folder [~/.mimpm]
# MIMIC_A_PATH       Base folder for all aliases. eg: .../aliases/
# MIMIC_B_DIR        Folder that contains mimic binaries .../aliases/
# MIMIC_A_DIR        Folder that contains current mimic aliases like eg: --log, --start, reload
# MIMIC_SHRD_DIR     Folder that contains shared functions that are sourced into alias environment
# MIMIC_CALLER       Called executable name(mimic) like git / netstat / ifconfig
# MIMIC_BIN          Original executable path /usr/bin/git
# MIMIC_ALIAS        Called alias name like: git --log  --log is an alias

## One line help info
function alias_help(){
    echo "Initialize ReactJS Typescript project"
}

## Multiline help doc for this alias
function alias_usage(){
   echo "USAGE: react init-ts <project-name>"
}

## Alias worker
#  If alias is prefixed with ! ( git ! log )
#  will be executed with original binary as /usr/bin/git log
##
function alias_do(){
  # Add/Modify/Preprocess/Postprocess parameters or functionality
  echo "Creating Typescript based ReactJS skeleton"
  npx create-react-app $1 --template typescript
  cd "$1"
  echo "Adding scss support"
  npm install node-sass --save
  echo "Installing react-router-dom"
  npm install react-router-dom --save
  echo "Installing @types"
  npm install --save typescript @types/node @types/react @types/react-dom @types/jest @types/react-router-dom
  cd -
  date
}
